namespace RevenueTemplateOrchestrator;

/// <summary>
/// Single source of truth for every DAX measure in the Revenue Tracker semantic model.
/// </summary>
public static class MeasureDefinitions
{
    public static readonly List<MeasureDefinition> All = new()
    {
        new MeasureDefinition("Fact_Revenue", "Total Revenue", "SUM(Fact_Revenue[Revenue])", "\\₹#,0;(\\₹#,0)", "Core"),
        new MeasureDefinition("Fact_Revenue", "Total Orders", "CALCULATE(COUNTROWS(Fact_Revenue), Fact_Revenue[IsRefund] = 0)", "#,0", "Core"),
        new MeasureDefinition("Fact_Revenue", "Total Refunds", "CALCULATE(COUNTROWS(Fact_Revenue), Fact_Revenue[IsRefund] = 1)", "#,0", "Core"),
        new MeasureDefinition("Fact_Revenue", "Refund Rate %", "DIVIDE([Total Refunds], [Total Refunds] + [Total Orders], 0)", "0.0%", "Core"),
        new MeasureDefinition("Fact_Revenue", "Average Order Value", "DIVIDE([Total Revenue], [Total Orders], 0)", "\\₹#,0.00", "Core"),
        new MeasureDefinition("Fact_Revenue", "Revenue Previous Month", "VAR CurrentMonthYear = MAX(Dim_MonthYear[MonthYear]) VAR PreviousMonthYear = CALCULATE(MAX(Dim_MonthYear[MonthYear]), FILTER(ALL(Dim_MonthYear), Dim_MonthYear[MonthYear] < CurrentMonthYear)) RETURN CALCULATE([Total Revenue], ALL(Dim_MonthYear), Dim_MonthYear[MonthYear] = PreviousMonthYear)", "\\₹#,0", "Growth"),
        new MeasureDefinition("Fact_Revenue", "Revenue MoM Growth %", "VAR Prev = [Revenue Previous Month] RETURN DIVIDE([Total Revenue] - Prev, Prev, BLANK())", "0.0%;-0.0%", "Growth"),
        new MeasureDefinition("Dim_Target", "Target Revenue", "SUM(Dim_Target[TargetRevenue])", "\\₹#,0", "Targets"),
        new MeasureDefinition("Dim_Target", "Target Achievement %", "DIVIDE([Total Revenue], [Target Revenue], 0)", "0.0%", "Targets"),
        new MeasureDefinition("Fact_Revenue", "Revenue Share by Channel %", "DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Dim_Channel)), 0)", "0.0%", "Channel"),

        // Overview HTML visuals.
        new MeasureDefinition("Fact_Revenue", "RevenueKpiHtml", "VAR r = FORMAT([Total Revenue], \"₹#,0\") VAR g = FORMAT([Revenue MoM Growth %], \"0.0%\") VAR c = IF([Revenue MoM Growth %] >= 0, \"#0E9E82\", \"#C43C6E\") RETURN \"<div style='font-family:Segoe UI,sans-serif;background:#fff;border-radius:14px;padding:20px 22px;box-shadow:0 2px 12px rgba(216,210,240,.55);height:100%;color:#1F1B2E'><div style='font-size:12px;font-weight:600;margin-bottom:14px'>Total Revenue</div><div style='font-size:32px;font-weight:600'>\"&r&\"</div><div style='font-size:11px;color:#8B879C;margin-top:4px'>Selected scope</div><div style='display:inline-block;margin-top:10px;padding:3px 8px;border-radius:999px;background:#F3F0FF;color:\"&c&\";font-size:11px;font-weight:600'>\"&g&\" vs prior month</div><div style='margin-top:18px;padding-top:14px;border-top:1px solid #ECEAF6;font-size:11px;color:#8B879C'>Target achievement <b style='color:#1F1B2E;font-size:14px'>\"&FORMAT([Target Achievement %],\"0%\")&\"</b></div></div>\"", "", "HTML"),
        new MeasureDefinition("Fact_Revenue", "RevenueByProductHtml", "VAR m = MAXX(ALL(Dim_Product[ProductName]), [Total Revenue]) RETURN \"<div style='font-family:Segoe UI,sans-serif;background:#fff;border-radius:14px;padding:20px 22px;box-shadow:0 2px 12px rgba(216,210,240,.55);height:100%;color:#1F1B2E'><div style='font-size:12px;font-weight:600;margin-bottom:14px'>Total Revenue by ProductName</div>\" & CONCATENATEX(VALUES(Dim_Product[ProductName]), VAR n=Dim_Product[ProductName] VAR v=[Total Revenue] VAR w=FORMAT(DIVIDE(v,m,0)*100,\"0\") RETURN \"<div style='margin:9px 0'><div style='display:flex;justify-content:space-between;font-size:10.5px;color:#6F6A80'><span>\"&n&\"</span><b style='color:#1F1B2E'>\"&FORMAT(v,\"₹#,0\")&\"</b></div><div style='height:8px;background:#F1EEFB;border-radius:6px;margin-top:4px'><div style='height:8px;width:\"&w&\"%;background:#7B5CFA;border-radius:6px'></div></div></div>\", \"\", [Total Revenue], DESC) & \"</div>\"", "", "HTML"),
        new MeasureDefinition("Fact_Revenue", "RevenueTrendHtml", "VAR mx=MAXX(ALL(Dim_Date[MonthYear]),[Total Revenue]) VAR bars=CONCATENATEX(VALUES(Dim_Date[MonthYear]),VAR v=[Total Revenue] VAR h=FORMAT(DIVIDE(v,mx,0)*100,\"0\") VAR lab=Dim_Date[MonthYear] RETURN \"<div style='flex:1;text-align:center'><div style='height:150px;display:flex;align-items:flex-end;justify-content:center'><div style='width:18px;height:\"&h&\"%;background:#F0629B;border-radius:6px 6px 2px 2px'></div></div><div style='font-size:9px;color:#8B879C;margin-top:6px'>\"&RIGHT(lab,5)&\"</div></div>\",\"\",Dim_Date[MonthYear],ASC) RETURN \"<div style='font-family:Segoe UI,sans-serif;background:#fff;border-radius:14px;padding:20px 22px;box-shadow:0 2px 12px rgba(216,210,240,.55);height:100%;color:#1F1B2E'><div style='font-size:12px;font-weight:600;margin-bottom:8px'>Total Revenue by MonthYear</div><div style='display:flex;gap:8px;align-items:stretch;height:185px'>\"&bars&\"</div></div>\"", "", "HTML"),
        new MeasureDefinition("Fact_Revenue", "TargetVsActualHtml", "VAR mx=MAXX(ALL(Dim_Product[ProductName]),MAX([Total Revenue],[Target Revenue])) RETURN \"<div style='font-family:Segoe UI,sans-serif;background:#fff;border-radius:14px;padding:20px 22px;box-shadow:0 2px 12px rgba(216,210,240,.55);height:100%;color:#1F1B2E'><div style='font-size:12px;font-weight:600;margin-bottom:14px'>Total Revenue and Target Revenue by ProductName</div><div style='display:flex;gap:12px;height:210px;align-items:flex-end'>\"&CONCATENATEX(VALUES(Dim_Product[ProductName]),VAR n=Dim_Product[ProductName] VAR r=[Total Revenue] VAR t=[Target Revenue] RETURN \"<div style='flex:1;display:flex;flex-direction:column;align-items:center;gap:5px'><div style='width:100%;display:flex;gap:3px;align-items:flex-end;height:180px'><div style='flex:1;height:\"&FORMAT(DIVIDE(r,mx,0)*100,\"0\")&\"%;background:#7B5CFA;border-radius:5px 5px 1px 1px'></div><div style='flex:1;height:\"&FORMAT(DIVIDE(t,mx,0)*100,\"0\")&\"%;background:#F0629B;border-radius:5px 5px 1px 1px'></div></div><div style='font-size:8.5px;color:#8B879C;text-align:center'>\"&LEFT(n,18)&\"</div></div>\",\"\",[Total Revenue],DESC)&\"</div><div style='font-size:10px;color:#8B879C;margin-top:4px'>● Revenue &nbsp; ● Target</div></div>\"", "", "HTML"),

        // Navigation contract: the HTML itself carries explicit, machine-readable
        // label-to-page metadata so CI validates the actual DAX HTML binding rather
        // than relying on arbitrary report JSON text. data-target values are the
        // authoritative Power BI page names used by the navigation visual.
        new MeasureDefinition("Fact_Revenue", "NavigationHtmlButtons", "RETURN \"<nav data-role='NavigationHtmlButtons' data-navigation-contract='Overview|RevenueOverview;Revenue|Revenue;Target|Target;Details|Details' style='display:flex;gap:8px;align-items:center;padding:10px 12px;background:#fff;border:1px solid #ECEAF6;border-radius:12px;box-shadow:0 2px 12px rgba(216,210,240,.55);font-family:Segoe UI,sans-serif'>\" & \"<a data-label='Overview' data-target='RevenueOverview' href='#RevenueOverview' style='padding:7px 13px;border-radius:999px;background:#7B5CFA;color:#fff;text-decoration:none;font-size:11px'>Overview</a>\" & \"<a data-label='Revenue' data-target='Revenue' href='#Revenue' style='padding:7px 13px;border-radius:999px;background:#fff;color:#1F1B2E;text-decoration:none;font-size:11px;border:1px solid #ECEAF6'>Revenue</a>\" & \"<a data-label='Target' data-target='Target' href='#Target' style='padding:7px 13px;border-radius:999px;background:#fff;color:#1F1B2E;text-decoration:none;font-size:11px;border:1px solid #ECEAF6'>Target</a>\" & \"<a data-label='Details' data-target='Details' href='#Details' style='padding:7px 13px;border-radius:999px;background:#fff;color:#1F1B2E;text-decoration:none;font-size:11px;border:1px solid #ECEAF6'>Details</a>\" & \"</nav>\"", "", "HTML"),

        // Revenue page: executive revenue summary with HTML cards.
        new MeasureDefinition("Fact_Revenue", "RevenuePageHtml", "VAR r=FORMAT([Total Revenue],\"₹#,0\") VAR o=FORMAT([Total Orders],\"#,0\") VAR a=FORMAT([Average Order Value],\"₹#,0\") VAR g=FORMAT([Revenue MoM Growth %],\"0.0%\") VAR gc=IF([Revenue MoM Growth %]>=0,\"#0E9E82\",\"#C43C6E\") RETURN \"<div style='font-family:Segoe UI,sans-serif;background:#fff;border-radius:14px;padding:22px;box-shadow:0 2px 12px rgba(216,210,240,.55);color:#1F1B2E'><div style='font-size:16px;font-weight:600'>Revenue</div><div style='font-size:10px;color:#8B879C;margin:3px 0 18px'>Performance summary</div><div style='display:grid;grid-template-columns:repeat(3,1fr);gap:12px'><div style='background:#FCFBFF;border:1px solid #ECEAF6;border-radius:10px;padding:14px'><span style='font-size:10px;color:#8B879C'>Total Revenue</span><div style='font-size:22px;font-weight:600;margin-top:5px'>\"&r&\"</div></div><div style='background:#FCFBFF;border:1px solid #ECEAF6;border-radius:10px;padding:14px'><span style='font-size:10px;color:#8B879C'>Orders</span><div style='font-size:22px;font-weight:600;margin-top:5px'>\"&o&\"</div></div><div style='background:#FCFBFF;border:1px solid #ECEAF6;border-radius:10px;padding:14px'><span style='font-size:10px;color:#8B879C'>Average Order Value</span><div style='font-size:22px;font-weight:600;margin-top:5px'>\"&a&\"</div></div></div><div style='margin-top:14px;padding:10px 12px;border-radius:9px;background:#F3F0FF;color:\"&gc&\";font-size:11px;font-weight:600'>\"&g&\" month-over-month growth</div></div>\"", "", "HTML"),
        new MeasureDefinition("Dim_Target", "TargetPageHtml", "VAR t=[Target Revenue] VAR r=[Total Revenue] VAR a=[Target Achievement %] VAR v=r-t VAR ac=IF(v>=0,\"#0E9E82\",\"#C43C6E\") RETURN \"<div style='font-family:Segoe UI,sans-serif;background:#fff;border-radius:14px;padding:22px;box-shadow:0 2px 12px rgba(216,210,240,.55);color:#1F1B2E'><div style='font-size:16px;font-weight:600'>Target</div><div style='font-size:10px;color:#8B879C;margin:3px 0 18px'>Revenue attainment</div><div style='font-size:30px;font-weight:600'>\"&FORMAT(t,\"₹#,0\")&\"</div><div style='font-size:10px;color:#8B879C;margin-top:2px'>Target revenue</div><div style='height:10px;background:#F1EEFB;border-radius:8px;margin:18px 0 8px'><div style='height:10px;width:\"&FORMAT(MIN(100,a*100),\"0\")&\"%;background:#7B5CFA;border-radius:8px'></div></div><div style='display:flex;justify-content:space-between;font-size:11px'><span>Achievement <b>\"&FORMAT(a,\"0.0%\")&\"</b></span><span style='color:\"&ac&\";font-weight:600'>Variance \"&FORMAT(v,\"₹#,0\")&\"</span></div></div>\"", "", "HTML"),
        new MeasureDefinition("Fact_Revenue", "DetailsPageHtml", "VAR rows=CONCATENATEX(TOPN(20,SUMMARIZE(Fact_Revenue,Fact_Revenue[TransactionID],Fact_Revenue[Date],Fact_Revenue[ProductID],Fact_Revenue[ChannelID],\"Rev\",SUM(Fact_Revenue[Revenue])),[Date],DESC),VAR id=Fact_Revenue[TransactionID] VAR dt=FORMAT(Fact_Revenue[Date],\"dd-MMM-yyyy\") VAR pid=Fact_Revenue[ProductID] VAR cid=Fact_Revenue[ChannelID] VAR rv=FORMAT([Rev],\"₹#,0\") RETURN \"<tr><td style='padding:8px;border-bottom:1px solid #ECEAF6'>\"&id&\"</td><td style='padding:8px;border-bottom:1px solid #ECEAF6'>\"&dt&\"</td><td style='padding:8px;border-bottom:1px solid #ECEAF6'>\"&pid&\"</td><td style='padding:8px;border-bottom:1px solid #ECEAF6'>\"&cid&\"</td><td style='padding:8px;border-bottom:1px solid #ECEAF6;text-align:right;font-weight:600'>\"&rv&\"</td></tr>\",\"\",[Date],DESC) RETURN \"<div style='font-family:Segoe UI,sans-serif;background:#fff;border-radius:14px;padding:20px 22px;box-shadow:0 2px 12px rgba(216,210,240,.55);height:100%;color:#1F1B2E'><div style='font-size:16px;font-weight:600'>Details</div><div style='font-size:10px;color:#8B879C;margin:3px 0 12px'>Latest transactions in the selected filter context</div><table style='width:100%;border-collapse:collapse;font-size:10px'><thead><tr style='background:#FCFBFF;color:#8B879C;text-align:left'><th style='padding:8px'>Transaction</th><th style='padding:8px'>Date</th><th style='padding:8px'>Product</th><th style='padding:8px'>Channel</th><th style='padding:8px;text-align:right'>Revenue</th></tr></thead><tbody>\"&rows&\"</tbody></table></div>\"", "", "HTML"),
    };
}

public record MeasureDefinition(
    string Table,
    string Name,
    string Expression,
    string FormatString,
    string DisplayFolder
);