table Fact_Revenue
	lineageTag = fact-revenue-table-001

	column TransactionID
		dataType: string
		lineageTag = fact-revenue-col-txnid
		summarizeBy: none
		sourceColumn: TransactionID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		lineageTag = fact-revenue-col-date
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProductID
		dataType: string
		lineageTag = fact-revenue-col-productid
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ChannelID
		dataType: string
		lineageTag = fact-revenue-col-channelid
		summarizeBy: none
		sourceColumn: ChannelID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag = fact-revenue-col-quantity
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag = fact-revenue-col-unitprice
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column Revenue
		dataType: double
		lineageTag = fact-revenue-col-revenue
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column IsRefund
		dataType: int64
		lineageTag = fact-revenue-col-isrefund
		summarizeBy: sum
		sourceColumn: IsRefund

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag = fact-revenue-col-currency
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	measure NavigationHtmlButtons = "RETURN \"<nav data-role='NavigationHtmlButtons' data-navigation-contract='Overview|RevenueOverview;Revenue|Revenue;Target|Target;Details|Details' style='display:flex;gap:8px;align-items:center;padding:10px 12px;background:#fff;border:1px solid #ECEAF6;border-radius:12px;box-shadow:0 2px 12px rgba(216,210,240,.55);font-family:Segoe UI,sans-serif'>\" & \"<a data-label='Overview' data-target='RevenueOverview' href='#RevenueOverview' style='padding:7px 13px;border-radius:999px;background:#7B5CFA;color:#fff;text-decoration:none;font-size:11px'>Overview</a>\" & \"<a data-label='Revenue' data-target='Revenue' href='#Revenue' style='padding:7px 13px;border-radius:999px;background:#fff;color:#1F1B2E;text-decoration:none;font-size:11px;border:1px solid #ECEAF6'>Revenue</a>\" & \"<a data-label='Target' data-target='Target' href='#Target' style='padding:7px 13px;border-radius:999px;background:#fff;color:#1F1B2E;text-decoration:none;font-size:11px;border:1px solid #ECEAF6'>Target</a>\" & \"<a data-label='Details' data-target='Details' href='#Details' style='padding:7px 13px;border-radius:999px;background:#fff;color:#1F1B2E;text-decoration:none;font-size:11px;border:1px solid #ECEAF6'>Details</a>\" & \"</nav>\""
		lineageTag = measure-navigation-buttons-html-001

	partition Fact_Revenue = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("Fact_Revenue_SampleData.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TransactionID", type text}, {"Date", type date}, {"ProductID", type text}, {"ChannelID", type text}, {"Quantity", Int64.Type}, {"UnitPrice", type number}, {"Revenue", type number}, {"IsRefund", Int64.Type}, {"Currency", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
